/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miprimerdb;

import java.awt.Image;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class Agencia extends javax.swing.JFrame {

    private Icon icono;
    private ImageIcon imagen;
    
    public Agencia() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.pintarImagen(this.lblFondo,  "src/Imagenes/images.jpeg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID_Agencia = new javax.swing.JLabel();
        lblNombreAgencia = new javax.swing.JLabel();
        lblModeloCarro = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtID_Agencia = new javax.swing.JTextField();
        txtNombreAgencia = new javax.swing.JTextField();
        txtUbicacion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAgencia = new javax.swing.JTable();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID_Agencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID_Agencia.setText("ID Agencia");
        getContentPane().add(lblID_Agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 9, -1, -1));

        lblNombreAgencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreAgencia.setText("Nombre de Agencia");
        getContentPane().add(lblNombreAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 69, -1, -1));

        lblModeloCarro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblModeloCarro.setText("Ubicacion");
        getContentPane().add(lblModeloCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 116, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefono.setText("Telefono");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 162, -1, -1));

        txtID_Agencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID_AgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtID_Agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 6, 255, -1));

        txtNombreAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAgenciaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 66, 255, -1));
        getContentPane().add(txtUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 113, 255, -1));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 159, 255, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 6, 92, -1));

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 65, 92, -1));

        btnEliminar.setText("Eliminar");
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 113, 93, -1));

        btnActualizar.setText("Actualizar");
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 159, 93, -1));

        jTAgencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Modelo", "Tipo", "Observacion"
            }
        ));
        jTAgencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAgenciaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTAgencia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 510, 145));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.jpeg"))); // NOI18N
        lblFondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblFondo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -1, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtID_AgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID_AgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID_AgenciaActionPerformed

    private void txtNombreAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAgenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAgenciaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.nuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        this.enviar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void jTAgenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAgenciaMouseClicked
        this.mouseclick();
    }//GEN-LAST:event_jTAgenciaMouseClicked


    private  void pintarImagen(JLabel lbl, String ruta){
    
           this.imagen = new ImageIcon(ruta);
           this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));
           lbl.setIcon(this.icono);
           this.repaint();
    }
    
    private void nuevo(){
    try{
       AgenciaBeans Ag=new AgenciaBeans();
       txtID_Agencia.setText(""+Ag.Incremento_Agencia()); 
       txtNombreAgencia.setText("");
       txtUbicacion.setText("");
       txtTelefono.setText("");


                     
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Error..."+ e.toString());  
    }
}
    
    private void enviar() {
    try {
        AgenciaBeans Ag = new AgenciaBeans();
        Ag.setID_Agencia(Integer.parseInt(txtID_Agencia.getText()));
        Ag.setNombreAgencia(txtNombreAgencia.getText());
        Ag.setUbicacion(txtUbicacion.getText());
        Ag.setTelefono(txtTelefono.getText());
        Ag.Insertar_Agencia();
        this.mostrar(jTAgencia,"Select * from Agencia");
        
        JOptionPane.showMessageDialog(null, "La información se ha guardado con éxito");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error de la transacción... RollBack: " + e.toString());
    }
}

private void mostrar(javax.swing.JTable JT, String sql){
    try{
        AgenciaBeans Ag = new AgenciaBeans();
        ResultSet rs;
        DefaultTableModel modelo=new DefaultTableModel();
        JT.setModel(modelo);
        rs=Ag.ConsultarTabla(sql);
        ResultSetMetaData rsMd;
        rsMd = rs.getMetaData();
        int cantcolumnas=rsMd.getColumnCount();
        JOptionPane.showMessageDialog(null,cantcolumnas);
        for (int i = 1; i <= cantcolumnas; i++) {
            modelo.addColumn(rsMd.getColumnLabel(i));
        }
        while(rs.next()){
            Object [] columna=new Object[cantcolumnas];
            for(int i = 0; i < cantcolumnas; i++){
                columna[i]=rs.getObject(i+1);
            }
            modelo.addRow(columna);
        }
    }catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error"+ e.toString());
    }

}
    private void mouseclick(){
     
     int fila=jTAgencia.getSelectedRow();
     txtID_Agencia.setText(jTAgencia.getModel().getValueAt(fila, 0).toString());
     txtNombreAgencia.setText(jTAgencia.getModel().getValueAt(fila, 1).toString());
     txtUbicacion.setText(jTAgencia.getModel().getValueAt(fila, 2).toString());
     txtTelefono.setText(jTAgencia.getModel().getValueAt(fila, 3).toString());

     
} 
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTAgencia;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID_Agencia;
    private javax.swing.JLabel lblModeloCarro;
    private javax.swing.JLabel lblNombreAgencia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtID_Agencia;
    private javax.swing.JTextField txtNombreAgencia;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
